export const ADD_MESSAGE = "ADD_MESSAGE"
export const DELETE_MESSAGE = "DELETE_MESSAGE"
export const SHOW_DETAIL = "SHOW_DETAIL"
export const CLOSE_DETAIL = "CLOSE_DETAIL"

export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS"
export const DELETE_ALL_MESSAGES_SUCCESS = "DELETE_ALL_MESSAGES_SUCCESS"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS"

